export const LESSONS_PENDING = 'LESSONS_PENDING';
export const LESSONS_FULFILLED = 'LESSONS_FULFILLED';
export const LESSONS_REJECTED = 'LESSONS_REJECTED';

export const ADD_LESSON_PENDING = 'ADD_LESSON_PENDING';
export const ADD_LESSON_FULFILLED = 'ADD_LESSON_FULFILLED';
export const ADD_LESSON_REJECTED = 'ADD_LESSON_REJECTED';

export const EDIT_LESSON_PENDING = 'EDIT_LESSON_PENDING';
export const EDIT_LESSON_FULFILLED = 'EDIT_LESSON_FULFILLED';
export const EDIT_LESSON_REJECTED = 'EDIT_LESSON_REJECTED';

export const DELETE_LESSON_PENDING = 'DELETE_LESSON_PENDING';
export const DELETE_LESSON_FULFILLED = 'DELETE_LESSON_FULFILLED';
export const DELETE_LESSON_REJECTED = 'DELETE_LESSON_REJECTED';

export const STORE_CURRENT_LESSON = 'STORE_CURRENT_LESSON';