export const CHAPTERS_PENDING = 'CHAPTERS_PENDING';
export const CHAPTERS_FULFILLED = 'CHAPTERS_FULFILLED';
export const CHAPTERS_REJECTED = 'CHAPTERS_REJECTED';

export const ADD_CHAPTER_PENDING = 'ADD_CHAPTER_PENDING';
export const ADD_CHAPTER_FULFILLED = 'ADD_CHAPTER_FULFILLED';
export const ADD_CHAPTER_REJECTED = 'ADD_CHAPTER_REJECTED';

export const EDIT_CHAPTER_PENDING = 'EDIT_CHAPTER_PENDING';
export const EDIT_CHAPTER_FULFILLED = 'EDIT_CHAPTER_FULFILLED';
export const EDIT_CHAPTER_REJECTED = 'EDIT_CHAPTER_REJECTED';

export const DELETE_CHAPTER_PENDING = 'DELETE_CHAPTER_PENDING';
export const DELETE_CHAPTER_FULFILLED = 'DELETE_CHAPTER_FULFILLED';
export const DELETE_CHAPTER_REJECTED = 'DELETE_CHAPTER_REJECTED';

export const STORE_CURRENT_CHAPTER = 'STORE_CURRENT_CHAPTER';