export const ANNOUNCEMENTS_PENDING = 'ANNOUNCEMENTS_PENDING';
export const ANNOUNCEMENTS_FULFILLED = 'ANNOUNCEMENTS_FULFILLED';
export const ANNOUNCEMENTS_REJECTED = 'ANNOUNCEMENTS_REJECTED';

export const ADD_ANNOUNCEMENT_PENDING = 'ADD_ANNOUNCEMENT_PENDING';
export const ADD_ANNOUNCEMENT_FULFILLED = 'ADD_ANNOUNCEMENT_FULFILLED';
export const ADD_ANNOUNCEMENT_REJECTED = 'ADD_ANNOUNCEMENT_REJECTED';

export const EDIT_ANNOUNCEMENT_PENDING = 'EDIT_ANNOUNCEMENT_PENDING';
export const EDIT_ANNOUNCEMENT_FULFILLED = 'EDIT_ANNOUNCEMENT_FULFILLED';
export const EDIT_ANNOUNCEMENT_REJECTED = 'EDIT_ANNOUNCEMENT_REJECTED';

export const DELETE_ANNOUNCEMENT_PENDING = 'DELETE_ANNOUNCEMENT_PENDING';
export const DELETE_ANNOUNCEMENT_FULFILLED = 'DELETE_ANNOUNCEMENT_FULFILLED';
export const DELETE_ANNOUNCEMENT_REJECTED = 'DELETE_ANNOUNCEMENT_REJECTED';

export const STORE_CURRENT_ANNOUNCEMENT = 'STORE_CURRENT_ANNOUNCEMENT';