export const COURSES_PENDING = 'COURSES_PENDING';
export const COURSES_FULFILLED = 'COURSES_FULFILLED';
export const COURSES_REJECTED = 'COURSES_REJECTED';

export const ADD_COURSE_PENDING = 'ADD_COURSE_PENDING';
export const ADD_COURSE_FULFILLED = 'ADD_COURSE_FULFILLED';
export const ADD_COURSE_REJECTED = 'ADD_COURSE_REJECTED';

export const EDIT_COURSE_PENDING = 'EDIT_COURSE_PENDING';
export const EDIT_COURSE_FULFILLED = 'EDIT_COURSE_FULFILLED';
export const EDIT_COURSE_REJECTED = 'EDIT_COURSE_REJECTED';

export const DELETE_COURSE_PENDING = 'DELETE_COURSE_PENDING';
export const DELETE_COURSE_FULFILLED = 'DELETE_COURSE_FULFILLED';
export const DELETE_COURSE_REJECTED = 'DELETE_COURSE_REJECTED';

export const STORE_CURRENT_COURSE = 'STORE_CURRENT_COURSE';