export const STUDENTS_PENDING = 'STUDENTS_PENDING';
export const STUDENTS_FULFILLED = 'STUDENTS_FULFILLED';
export const STUDENTS_REJECTED = 'STUDENTS_REJECTED';

export const ADD_STUDENT_PENDING = 'ADD_STUDENT_PENDING';
export const ADD_STUDENT_FULFILLED = 'ADD_STUDENT_FULFILLED';
export const ADD_STUDENT_REJECTED = 'ADD_STUDENT_REJECTED';

export const STORE_CURRENT_STUDENT = 'STORE_CURRENT_STUDENT';